name: sample_pj
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  annotation_indexer_annotation:
    path: ../annotation_indexer_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  annotation_indexer:
    path: ../annotation_indexer

flutter:
  uses-material-design: true
